### ISSUE TITLE
服务端崩溃

### ISSUE THREAD

**Issue by H2Sxxa** [Ideal-Ontology/GensokyoOntologics#5]
<details><summary>Logs</summary>

```java
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 23-10-29 下午9:34
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:37) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading,re:mixin,pl:mixin:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_361] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_361] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_361] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_361] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[server-release.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [server-release.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [server-release.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [server-release.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_361] {}
-- MOD gensokyoontology --
Details:
	Caused by 0: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: github.thelawf.gensokyoontology.common.item.danmaku.RiceShot.<init>()void/newInvokeSpecial
		at github.thelawf.gensokyoontology.core.init.ItemRegistry.<clinit>(ItemRegistry.java:520) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at github.thelawf.gensokyoontology.GensokyoOntology.<init>(GensokyoOntology.java:60) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_361] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_361] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_361] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_361] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_361] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_361] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_361] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_361] {}

	Caused by 1: java.lang.IllegalAccessError: no such constructor: github.thelawf.gensokyoontology.common.item.danmaku.RiceShot.<init>()void/newInvokeSpecial
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_361] {}
		at github.thelawf.gensokyoontology.core.init.ItemRegistry.<clinit>(ItemRegistry.java:520) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at github.thelawf.gensokyoontology.GensokyoOntology.<init>(GensokyoOntology.java:60) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_361] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_361] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_361] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_361] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_361] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_361] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_361] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_361] {}

	Caused by 2: java.lang.NoClassDefFoundError: net/minecraft/entity/IRendersAsItem
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_361] {}
		at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_361] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_361] {}
		at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_361] {}
		at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_361] {}
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_361] {}
		at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_361] {}
		at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_361] {}
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_361] {}
		at github.thelawf.gensokyoontology.core.init.ItemRegistry.<clinit>(ItemRegistry.java:520) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at github.thelawf.gensokyoontology.GensokyoOntology.<init>(GensokyoOntology.java:60) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_361] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_361] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_361] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_361] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_361] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_361] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_361] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_361] {}

	Mod File: gensokyoontology-forge-1.16.5-preview-0.0.3.jar
	Failure message: gensokyoontology (gensokyoontology) has failed to load correctly
		java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: github.thelawf.gensokyoontology.common.item.danmaku.RiceShot.<init>()void/newInvokeSpecial
	Mod Version: forge-1.16.5-preview-0.0.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraft.entity.IRendersAsItem
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_361] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_361] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_361] {}
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_361] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_361] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_361] {}
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_361] {}
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_361] {}
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_361] {}
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_361] {}
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_361] {}
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_361] {}
	at github.thelawf.gensokyoontology.core.init.ItemRegistry.<clinit>(ItemRegistry.java:520) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
	at github.thelawf.gensokyoontology.GensokyoOntology.<init>(GensokyoOntology.java:60) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_361] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_361] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_361] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_361] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_361] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_361] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_361] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_361] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_361] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_361] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_361] {}
```
</details>

使用 [86260bd](https://github.com/Ideal-Ontology/GensokyoOntologics/commit/86260bdd890342640729fb124cd28e00aaf2640a) Action编译版本

**Comment by H2Sxxa** [comment]
测试了一下礼弹，也是如此

<details>

```java
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 23-10-29 下午10:16
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:71) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:37) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_361] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_361] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_361] {}
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_361] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:37) ~[server-release.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.1.3.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.1.3.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:49) [server-release.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:46) [server-release.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:43) [server-release.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_361] {}
-- MOD gensokyoontology --
Details:
	Caused by 0: java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: github.thelawf.gensokyoontology.common.item.danmaku.TalismanShot.<init>()void/newInvokeSpecial
		at github.thelawf.gensokyoontology.core.init.ItemRegistry.<clinit>(ItemRegistry.java:516) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at github.thelawf.gensokyoontology.GensokyoOntology.<init>(GensokyoOntology.java:62) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_361] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_361] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_361] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_361] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_361] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_361] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_361] {}

	Caused by 1: java.lang.IllegalAccessError: no such constructor: github.thelawf.gensokyoontology.common.item.danmaku.TalismanShot.<init>()void/newInvokeSpecial
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:483) ~[?:1.8.0_361] {}
		at github.thelawf.gensokyoontology.core.init.ItemRegistry.<clinit>(ItemRegistry.java:516) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at github.thelawf.gensokyoontology.GensokyoOntology.<init>(GensokyoOntology.java:62) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_361] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_361] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_361] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_361] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_361] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_361] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_361] {}

	Caused by 2: java.lang.NoClassDefFoundError: net/minecraft/entity/IRendersAsItem
		at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_361] {}
		at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_361] {}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?] {re:classloading}
		at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_361] {}
		at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_361] {}
		at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_361] {}
		at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_361] {}
		at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_361] {}
		at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_361] {}
		at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_361] {}
		at github.thelawf.gensokyoontology.core.init.ItemRegistry.<clinit>(ItemRegistry.java:516) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at github.thelawf.gensokyoontology.GensokyoOntology.<init>(GensokyoOntology.java:62) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_361] {}
		at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_361] {}
		at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_361] {}
		at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_361] {}
		at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_361] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[forge:36.2] {re:classloading}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_361] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_361] {}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_361] {}

	Mod File: gensokyoontology-forge-1.16.5-preview-0.0.3.jar
	Failure message: gensokyoontology (gensokyoontology) has failed to load correctly
		java.lang.BootstrapMethodError: java.lang.IllegalAccessError: no such constructor: github.thelawf.gensokyoontology.common.item.danmaku.TalismanShot.<init>()void/newInvokeSpecial
	Mod Version: forge-1.16.5-preview-0.0.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.ClassNotFoundException: net.minecraft.entity.IRendersAsItem
Stacktrace:
	at java.lang.ClassLoader.findClass(ClassLoader.java:523) ~[?:1.8.0_361] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_361] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:106) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_361] {}
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_361] {}
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_361] {}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:138) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98) ~[modlauncher-8.1.3.jar:?] {re:classloading}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_361] {}
	at java.lang.invoke.MethodHandleNatives.resolve(Native Method) ~[?:1.8.0_361] {}
	at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975) ~[?:1.8.0_361] {}
	at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000) ~[?:1.8.0_361] {}
	at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394) ~[?:1.8.0_361] {}
	at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750) ~[?:1.8.0_361] {}
	at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477) ~[?:1.8.0_361] {}
	at github.thelawf.gensokyoontology.core.init.ItemRegistry.<clinit>(ItemRegistry.java:516) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
	at github.thelawf.gensokyoontology.GensokyoOntology.<init>(GensokyoOntology.java:62) ~[gensokyoontology:forge-1.16.5-preview-0.0.3] {re:classloading}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_361] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_361] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_361] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_361] {}
	at java.lang.Class.newInstance(Class.java:442) ~[?:1.8.0_361] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:67) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:106) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) ~[?:1.8.0_361] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) ~[?:1.8.0_361] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_361] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1067) ~[?:1.8.0_361] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1703) ~[?:1.8.0_361] {}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:172) ~[?:1.8.0_361] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Linux (amd64) version 6.1.0-11-amd64
	Java Version: 1.8.0_361, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1269755584 bytes (1210 MB) / 1958215680 bytes (1867 MB) up to 6703546368 bytes (6393 MB)
	CPUs: 4
	JVM Flags: 2 total; -Xms1024M -Xmx7192M
	ModLauncher: 8.1.3+8.1.3+main-8.1.x.c94d18ec
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/server-release.jar object_holder_definalize PLUGINSERVICE 
		/server-release.jar runtime_enum_extender PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/server-release.jar capability_inject_definalize PLUGINSERVICE 
		/server-release.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/server-release.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: net.minecraftforge:36.2.39
	FML Language Providers: 
		javafml@36.2
		minecraft@1
	Mod List: 
		forge-1.16.5-36.2.39-server.jar                   |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		forge-1.16.5-36.2.39-universal.jar                |Forge                         |forge                         |36.2.39             |CREATE_REG|Manifest: 22:af:21:d8:19:82:7f:93:94:fe:2b:ac:b7:e4:41:57:68:39:87:b1:a7:5c:c6:44:f9:25:74:21:14:f5:0d:90
		gensokyoontology-forge-1.16.5-preview-0.0.3.jar   |gensokyoontology              |gensokyoontology              |forge-1.16.5-preview|ERROR     |Manifest: NOSIGNATURE
	Crash Report UUID: 90e3a18f-e8a2-4240-a072-03db51c7a63e
```

</details>

**Comment by H2Sxxa** [comment]
据说是修复了，那就先关了罢（
